Updating Instruction Panel
med-material/Whack_A_Mole_VR pull request #208
Opened 2022-09-22 11:48 UTC by Xav1204

We needed to update the instruction panel to show to the patient what is the good position to have in order to play the game. So the instruction panel is now updating but we also need to make a fade out to the calibration panel. However, we will wait the fade In/Out script manager before doing this.

2022-09-22 12:16 UTC, hendrikknoche commented
> 
little English feedback:  the correct/right position. "The good position" is not a thing. 👍

2022-09-22 13:00 UTC, bastianilso requested changes
Thanks for the pull request, @Xav1204. 🌴

Few comments:

- Instead of creating a new folder inside Prefabs called `Image/` and put the assets there, I would like you to move the `person-resting-position.png` into `Assets\Textures\UI_icons` where the rest of our UI Icons lives. It's important that we maintain consistency as much as possible with the existing structure.
![image](https://user-images.githubusercontent.com/3967945/191749245-8e0770ce-b44b-4bef-b2eb-e2526d01771a.png)

- With the updated layout, I think we need better names for our UI containers. The object "Text container" now contains images, so the name doesnt make much sense. And "Images container" now contains both an image **and**  the "Text container". 
![image](https://user-images.githubusercontent.com/3967945/191752310-1a8ab8af-7248-4814-a38c-f6d07f07f43e.png)

- We are missing a border around the instructions. You can use `rectangle-outline.png` to create this. (this is how we e.g. draw the motorspace borders).

2022-09-23 07:54 UTC, Xav1204 commented
@bastianilso it's good, I made the changes.

2022-09-23 08:06 UTC, bastianilso requested changes
Hi Xav, the thickness and color of the border is a bit off, compared to the design wire in #199 . You can increase the "Pixel per unit multiplier" to achieve a thinner thickness.

2022-09-23 08:53 UTC, Xav1204 commented
@bastianilso tell me if it's good for you.

2022-09-23 09:01 UTC, bastianilso commented
@Xav1204 for these kind of visual changes, it would be easier if you made a screenshot of your changes. 🙂 Here I did it for you:

![image](https://user-images.githubusercontent.com/3967945/191925856-12c27632-bf16-487d-b5cc-f59dada2e31d.png)

For reference, this is the design wire:

![image](https://user-images.githubusercontent.com/3967945/191925883-8730bfe3-c24f-4452-bd1e-911228360bcd.png)

As is clear from the comparison, the position of the left image and the size of the text to the right are not matching the design wire.  I can also see that the text needs to be updated in the implementation (to the new text shown in the image). You seem to have fairly good grasp of the Unity UI system already, but I would like you to aim for higher precision with regards to matching how text and images are laid out on the wire.  Thanks!  👍

2022-09-28 07:07 UTC, bastianilso commented
OK so the current commit looks like this: (@Xav1204 please upload screenshots when you update your pull request, so I can follow along - I dont know otherwise whether you are awaiting a review from me. 🙂 )

![image](https://user-images.githubusercontent.com/3967945/192711062-1a474df3-7ad0-4e34-b4bd-1b84b1a6577e.png)

We concluded that it might be better to make it smaller because the current instructions are approaching the "blurry zone" of VR. @Xav1204 let me know when you have an update. thanks!

2022-09-28 08:45 UTC, Xav1204 commented
![image](https://user-images.githubusercontent.com/73820233/192732240-47f3a3a3-5f31-492a-96b8-e0e3b3f55e19.png)
We have now this instruction panel. in the VR headset, we have always the 'blurry zone' but the letters are readable.

2022-09-28 08:51 UTC, Xav1204 commented
@bastianilso it's good, I finished the new panel and I also added the fadeOut effect.

2022-09-28 09:24 UTC, bastianilso commented
Think about your smartphone, for example. When you unlock the screen, how fast that animation actually is? It's usually around 400-600ms, sometimes even faster. This is the kind of speed we are targeting. 🙂

2022-09-29 06:25 UTC, Xav1204 commented
![InstructionPanelTransition](https://user-images.githubusercontent.com/73820233/192954971-f9615a4f-051f-4dd8-966b-4009f7935543.gif)
@bastianilso I think that it's good now.

2022-09-29 06:53 UTC, bastianilso requested changes
looks good @Xav1204, i just have minor comments left now.

2022-09-29 06:53 UTC, bastianilso commented on Assets/Scripts/Game/HmdCalibration.cs
> +    }
looks good. if you want, instead of having an arbitrary number (3), we could define a private variable we call `speed` and put the 3 number in there.

2022-09-29 06:53 UTC, bastianilso commented on Assets/Scripts/Game/HmdCalibration.cs
> +    private void closeInstructionPanel(){
CamelCase, thanks

2022-09-29 07:02 UTC, Xav1204 commented
![image](https://user-images.githubusercontent.com/73820233/192962082-a2b6cc5f-ccd0-4bc2-88b5-903e8ed65a55.png)
@bastianilso it's good. I put the transition speed by default at 3.

2022-09-29 07:07 UTC, bastianilso approved these changes
All good! 👍 thanks for sticking through.

2022-09-29 07:07 UTC, Xav1204 commented
![image](https://user-images.githubusercontent.com/73820233/192962826-a9990a56-635f-48a0-a619-75267424af1b.png)
@bastianilso just a little change. Transition speed variable looks like the time of the transition. I just changed the variable name in ratio speed, it's more understandable.

2022-09-29 07:07 UTC, merged