Randomly Mole Spawner System
med-material/Whack_A_Mole_VR pull request #210
Opened 2022-09-27 10:51 UTC by Xav1204

We needed to add a small animation on the wall to make the experience more immersive. Now, the mole spawn randomly on the wall surface.

What we still need to do: - Add a fadeout transition for the countdown panel
		                         - Add a fadein effect for the mole when they spawn

2022-09-27 10:57 UTC, Xav1204 commented
[Animation.zip](https://github.com/med-material/Whack_A_Mole_VR/files/9654734/Animation.zip)

I made a gif to show the animation but it was too heavy so I compressed it.

2022-09-27 13:49 UTC, hendrikknoche commented
great. For future submissions try to e.g. reduce the resolution because the steps of downloading and unzipping defeat the purpose of having a visual here for easy browsing. :-)

2022-09-28 06:51 UTC, Xav1204 commented
![MoleSpawner](https://user-images.githubusercontent.com/73820233/192708347-7a093bbc-5202-4ff7-aef5-9faa025885b3.gif)
I did it again. I think that it will be better now.

2022-09-28 07:08 UTC, bastianilso commented
Hi @Xav1204, can you try speeding it up by 2x  (double speed)? Just want to see how it looks, compared to current animation you uploaded. thanks!

2022-09-28 11:07 UTC, Xav1204 commented
![MoleSpawner](https://user-images.githubusercontent.com/73820233/192764007-aedc342a-3c7c-48e8-b92b-fe54299896a2.gif)
@bastianilso Is it enough fast for you?

2022-09-28 11:54 UTC, bastianilso requested changes
@Xav1204 the visual is now looking perfect, I like the speed, it's is now very similar to Trail it. 👍

I've looked at your code, and I can see you have some concerns about not starting the game until the animation is done.

2022-09-28 11:54 UTC, bastianilso commented on Assets/Scripts/Game/GameDirector.cs
> +            }
I think we can implement this in a cleaner way.
If you read this if statement aloud, you get the following information.

- if Pattern Manager tells us the Pattern is loaded, then proceed. (very clear)
- if a boolean called `canPlaying`  is true, then start the game. (not clear)

the problem with the bool `canPlaying`, is that it does not translate clearly - who is saying the game can play? if the bool is false, we would have to investigate why. We cannot simply "read" from the variable name itself why.

In addition, the bool creates new interaction between `WallManager.cs` and `GameDirector.cs`. 
But WallManager cannot dictate GameDirector. The GameDirector is the director of the game afterall (by name and thus convention in Whack-A-Mole).

Anyway, now the animation is quiet fast. So I don't think it warrants the extra code complexity (if you disagree, or have a technical reason feel free to explain). Also this code would only affect custom patterns, not random moles.

2022-09-28 11:54 UTC, bastianilso commented on Assets/Scripts/Game/HmdCalibration.cs
> +                calibrated = true;
this change is not related and should be removed or split into its own "style nit" commit.

2022-09-28 11:54 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +
Why does this use underscore and all small caps in its function name? (by convention we use CamelCase for function names). 

Why is this function necessary for the animation by the way? (not clear to me from the commit message).
I think we should aim to reduce this complexity to have moles appear randomly on a board a bit. 🙂

2022-09-28 11:54 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +            }
would a simplification of this be `while(arrayMole.Length == 0)` then?

2022-09-28 11:54 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +    private IEnumerator moleSpawner(List<GameObject> list){
CamelCase function name.
Also, function names typically do something, so they should reflect this.
For example calling a function called  `SpawnMoles()` on `WallManager`, reads that "WallManager Spawns Moles". but you wall manager cannot "mole spawner". MoleSpawner sounds like more like a class name. 🙂

2022-09-29 06:42 UTC, Xav1204 commented
@bastianilso I pushed the updates. I also commented the code with the explanations of my choices.

2022-09-29 07:13 UTC, bastianilso commented
@Xav1204 Could you please respond directly to my questions in the pull request itself?

![image](https://user-images.githubusercontent.com/3967945/192964125-6ee3e115-ef88-4258-8348-b78d4ef4065e.png)

I think it's fine with the code comments too. By convention we either use code comments if 
a) we want to document what a function does, or 
b) if we introduce a hack/do something unconventional/do a workaround of some kind.

2022-09-29 07:21 UTC, Xav1204 commented
@bastianilso I didn't see any questions in your last comment. Do you want that I respond to the question about the interest of the  Chunked Lists?

2022-10-10 12:18 UTC, bastianilso requested changes
Hi @Xav1204, I'm not convinved we need separate logic that splits the list into two, just to speed up the animation. See my comment/suggestion for simpler/alternative implementation.

2022-10-10 12:18 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +
Instead of having a dedicated function to divide the list into two, can't you just use `Random.Range `and `.RemoveAt(i)` twice in the IEnumerator function?

2022-10-25 07:29 UTC, Xav1204 commented
@bastianilso it's also good for the mole spawn animation. We just need to see the behavior of the animation after having solved the conflicts

2022-10-26 06:41 UTC, bastianilso requested changes
Hi @Xav1204, there are some changes in here that are unrelated to your pull request. It looks like  some changes to LICENSE, GameDirector and PlayerPanel.cs has creeped into the commit.  Is it because the branch needs rebasing? These changes will need to be removed from the commit.

in addition there are some comments:

2022-10-26 06:41 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +                list.RemoveAt(i);
Converting a list to an array within a long for loop, sounds quiet intensive. Why do you need `tmpList`? Can't we do all these operations on `list` itself?

2022-10-26 06:41 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +    private IEnumerator FillingWall(List<GameObject> list){
Could rename to `FillWall` to follow the car analogy better (car.drive, car.fillwall...)

2022-10-26 09:08 UTC, closed without merging