Data Saving System
med-material/Whack_A_Mole_VR pull request #214
Opened 2022-10-05 10:45 UTC by Xav1204

We needed to update UI during a save to show to the therapist that the save is incomplete. So for this, we have a warning message panel that appear when we try to quit the app during the save. Moreover, we have an indicator of the total files that we need to save and how many are saved. When the save is done, we can restart a game.
There will maybe be some functions that will disappear if we succeed to implement the multi-save system.

2022-10-05 11:55 UTC, bastianilso requested changes
Hi @Xav1204, behavior is fine but we need to come up with a better code design. See my comments.

2022-10-17 07:11 UTC, Xav1204 commented
@bastianilso  I think that it's good now for the warning panel. 
I used 3 Unity Events : 
1. The first one is used to manage the spawn of the start game button in order to restart a game after the end of the save. However, as we want to create a multi save system  in order to prevent the therapist to wait until the end of the save, this Event should disappear in the future and we will hand over the Reset function in GameStateContainer.cs.
2. The second one is used to call the function OpenWarningPanel in the TherapistUI script in order to open the panel and inform the therapist that is save is not done and he need to wait until the end of this one. Moreover, we need to disable the exit button because if the therapist click on this button multiple times, the app can crash and the datas will be lost. However, as the app will be closed after the save, it's not necessary to reactivate this button.
3. The last event is used to close the app if the save is done. It can close the app when the warning panel is opened or closed.

We have also a bool value in our Unity Event in order to manage the opening of the warning panel and the closing of the app if this one is opened.

Finally, to know if the save is done, I look if the last label in the logstore is clear and if it's the case, the save is done.

Please, let me know if it's look right for you now.

2022-10-18 20:21 UTC, bastianilso requested changes
Hi @Xav1204, I'm happy you tried out implementing this with Unity Events. However, I think you should try to think harder about the engineering here. Try to draw for yourself, how you envision that the classes communicate to each other. Maybe get a second opinion from @lucasmnt too. I added some comments that I hope can guide you a bit.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +}
@Xav1204 think more logically about your definitions of enums and classes.

 - `LoggingManager.SaveSatus` - what would `SaveStatus.Start` mean? I dont think its clear. "Start" is not a status. "SaveStatus.Started" would read as "the save status has started". "SaveSatus.Starting" would read as if the save is in the process of starting. "SaveStatus.Start" is something undefined, it could mean either of those two.  But maybe you actually want to say `SaveStatus.Saving` ? (which reads as "the save status is in that we are saving").
Apply same logic to "Finish" here. ("Finished" reads better).

- `LogSaveResult` - ask yourself, as someone who dont know how it is used, what do you expect to find in here? Judging from the title, to me, I would expect 1) that its a class containing results from saving logs, implying that 2) those results are only sent when logs are finished saving and 3) that it contains something indication whether the save was successful and maybe info about what was saved. But when I look at what this class contains, it has none of these. So perhaps we need a better name here? The point is, think about the name of the class and how it represents its content.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +
what is this for? Why does it hardcode the word "`Sample`" ? not clear to me.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +	public OnSaveNotDone onSaveNotDone;
Why do we need two separate signals for when saving is done and when saving is not done?
We should be fine with just one signal, which is emitted whenever we have an update about saving.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +
Why do we have a signal called `CloseApplication`? Judging solely by the name, it sounds to me like LoggingManager would send this signal whenever someone tries to close the application. However, LoggingManager only does logging, it has nothing to do with handling the closing of the application.
(Also you break the convention, you should e.g. say `OnCloseApplication` - but not sure we need this).

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +    private LogSaveResult logSaveResult = new LogSaveResult();
instead of keeping a private instance of LogSaveResult around and updating its values, you should instead follow the convention seen in e.g. LaserMapper about MotorSpaceInfo. You should instantiate LogSaveResult whenever you need to emit a signal and assign its contents with values from the constructor.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +        }
We can't just assume that the last log that we save always is called `Sample` - LoggingManager by design does not make assumptions like this. There must be a cleaner way through which you can find out whether we are done saving.

2022-10-18 20:21 UTC, bastianilso commented on Assets/Scripts/UI/TherapistUi.cs
> +
If TherapistUI is listening to events from LoggingManger, then surely we wont need to serializeField loggingManager. This is the point of relying on UnityEvents.

2022-10-18 20:21 UTC, bastianilso commented on Assets/Scripts/UI/TherapistUi.cs
> +        loggingManager.CheckSaveStatus();
I think it would be cleaner if this was handled by applicationManager, so therapistUi doesnt have to deal with loggingManager directly.

2022-10-18 20:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +    }
There should be no need to check anything within an `Update()` function to solve this task. Generally speaking LoggingManger does not need to do something within Unity's frameclock. This looks like a workaround.

2022-10-18 20:28 UTC, bastianilso commented
@Xav1204 this was a lot of comments, but we are also dealing with a data saving system which introduce a lot of new interaction between classes in Whack-A-Mole, that we need to get right. :) 

Please respond in-line to the comments i provided above with rationales, suggestions, questions so I follow your train of thought on this, thanks!

2022-10-19 08:51 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +}
@bastianilso I changed the variables and classes names with Lucas. So I think that it's clearer now.

2022-10-19 08:54 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +
Now, with this line, we recuperate the last key in logslist : `lastLabel = logsList.Keys.Last();`.
Logslist keys are the labels (meta, event, sample), so now, if we add a new label, the code will be recursive and will check if this new label is cleared.

2022-10-19 08:57 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +	public OnSaveNotDone onSaveNotDone;
As I said, the first Event is used to reset the start game container with the start game button when the save is done. When the multi save system will be implemented, this event will disappear.

2022-10-19 12:03 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +    }
Now, I use an IEnumerator that is waiting for my variable SaveStatus is different to "IsSaving" to close the app.

2022-10-19 12:05 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +
This event has disappeared because the IEnumerator in TherapistUi script is adequate for our case.

2022-10-19 12:10 UTC, Xav1204 commented
@bastianilso I think that it's good now. I simplified the code at the most that I could.

So please tell me if you it looks right for you and don't hesitate to tell me also if you have any questions or doubts.

2022-10-20 21:33 UTC, bastianilso commented
thanks @Xav1204 . I will take a look at this on monday and get back to you. There are still some communication I think we can simplify. The main thing is that TherapistUI should not contain logic about quitting, its merely handling IO between User Interface and managers. In addition, ApplicationManager should subscribe and react to updates from LoggingManager, and behave appropriately based on which saving state LoggingManager is reporting. LoggingManager is only reporting a saving state, whoever listens to this information will decide which parts of the information is relevant to them. LoggingManager does not know about restarting applications, it just announces its own state. Here is a conceptual overview:

**LoggingManager**: should only report its saving state, e.g. is CSV saving, CSV saving progress,  is CSV done, did CSV saving fail..

**TherapistUI/GameStateContainer**: listens to LoggingManager's updates and updates UI based on state information from LoggingManager saving. (Saving....1/3) etc.

**ApplicationManager:** Listens to LoggingManager's updates. If the CloseGame() is called while LoggingManager reported CSV is still saving, it prevents the game from quitting and instead asks TherapistUI to show "Saving Data.." Dialog. When LoggingManager informs ApplicationManager that saving is done and a previous call to ClosedGame() has been observed, ApplicationManager can then safely quit the game.

2022-10-21 08:19 UTC, hendrikknoche commented
@bastianilso, should the loggingManager also report on whether it is currently in the state of continuously logging - which will require saving at some point?

2022-10-21 21:13 UTC, bastianilso commented
@hendrikknoche  good point. LoggingManager could report a "Logging" state, it would be very logical and expected. It would enable us to e.g. react if users try to exit Whack-A-Mole while a game is running. We could for example then stop the game and show the "Saving data.." dialog and finally quit afterwards.

2022-10-24 10:33 UTC, bastianilso requested changes
see comments

2022-10-24 10:33 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +}
need 3 information:
- state
- how many files are saved
- how many files are left to be saved.

rename to SaveStateInfo

2022-10-24 10:33 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +    public SaveStateSender saveStateSender = new SaveStateSender();
Rename to SaveStateInfo

2022-10-24 10:33 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +        onSaveStateChanged.Invoke(saveStateSender);
https://github.com/med-material/Whack_A_Mole_VR/blob/master/Assets/Scripts/Pointers/LaserMapper.cs#L260

It's also possible instantiate a new SaveStateInfo box and then pass values from an existing internal SaveStateInfo box to that, at construction time.
`
onSaveStateChanged.Invoke(new SaveStateInfo { saveStateInfo }); `

2022-10-25 07:12 UTC, Xav1204 commented
@bastianilso it's good, all the improvements have been made.

2022-10-26 06:27 UTC, bastianilso requested changes
@Xav1204 nice, i have some additional comments, see below.

2022-10-26 06:27 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +        if(logStore.Label == lastLabel)
The logic will be cleaner if we compare the numberOfSavedFiles counter to totalNumberOfFilesToSaved counter. The numberOfSavedFiles should be updated from within the CSV writing callback and not from `SaveAllLogs()`.

2022-10-26 06:27 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +    public int numberOfFilesLeftToSave;
instead of numberOfFilesLeftToSave, I think we should have "totalNumberOfFilesToSave". Otherwise, the two numbers are just reverse of each other.

2022-10-26 06:27 UTC, bastianilso commented on Assets/Scripts/Application/ApplicationManager.cs
> +        saveState = s.status.ToString();
Why not store the saveState as the `LoggingManager.SaveStatus` enum instead of a string? making a string conversion seems unnecessary and kills the point of using an enum.

2022-10-26 06:27 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +}
If we have a SaveStatus called ReadyToSave, then LoggingManager should emit a signal indicating this state at startup.

2022-10-26 06:27 UTC, bastianilso commented on Assets/Scripts/Application/ApplicationManager.cs
> +        yield return new WaitUntil(() => saveState == "Saved" || saveState == null);
I think saveState is supposed to be "ReadyToSave" here (the enum is never null).

2022-10-26 08:21 UTC, Xav1204 commented
@bastianilso I've made the changes, I hope that it's that you really want especially with the LoggingManager.SaveStatus enum in applicationManager. Moreover, as you've merged a pull request, a conflict with the mainscene.unity appeared and you sent us a mail and explained us how to solve it but I didn't succeed to manage the conflict. If you're at the university tomorrow, could you please come and explain to me and Lucas how to solve this conflict in the future please ?

2022-11-02 08:02 UTC, bastianilso requested changes
Just minor stuff now @Xav1204, have a look at the comments below.

As for your question about the mainscene.Unity, the file is binary so we can't rebase it. In some cases we can just make changes to prefabs, but in this case because we deal with information exchange across many different objects in the scene, we will need to re-make the changes once again in the new mainscene.unity. Please apply the minimal number of changes and as cleanly as possible. 

- make a copy of your current scene, put it outside the git folder.
- Reset changes made to mainscene.unity and rebase your code.
- open the new mainscene.unity and the copy of your old mainscene.unity (bring it back to the git folder)
- re-apply the necessary changes you made.
- verify that the data saving system works as expected.
- delete the scene copy.

We will aim to have this branch merged with master as the next, so you will only have to do this once.

2022-11-07 14:28 UTC, closed without merging