Add Inside and Outside Motorspace Logs
med-material/Whack_A_Mole_VR pull request #215
Opened 2022-10-05 10:51 UTC by Xav1204

We needed to log in our csv file when the controller is Inside or Outside the motorspace to get better analysis of the games.

2022-10-05 12:46 UTC, bastianilso requested changes

2022-10-05 12:46 UTC, bastianilso commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +        }
Hi @Xav1204 it is not clear to me why we would need to redefine the PointerHoverBoundaries function and make BubbleDisplay inherit Pointer, just to do some logging. 

Why not put the `loggerNotifier.NotifyLogger() ` statement inside the `if (render)` and `if (!render)`  inside the `Update()` function of BubbleDisplay?

https://github.com/med-material/Whack_A_Mole_VR/blob/master/Assets/Scripts/Pointers/BubbleDisplay.cs#L106

2022-10-06 09:27 UTC, Xav1204 commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +        }
@bastianilso it's good, I put in the loggerNotifier inside the if conditions directly.

2022-10-06 19:56 UTC, bastianilso requested changes
Thanks for the changes @Xav1204, this is looking better, but I still think we can simplify this further, see code comments.

2022-10-06 19:56 UTC, bastianilso commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +                    {"ControllerHoverBoundaries", controllerInsideBoundaries}
We won't need a dedicated column called `ControllerHoverBoundaries` in our log files. For now this event can just be logged with no additional columns, like exemplified below.

```
loggerNotifier.NotifyLogger("Pointer Inside MotorSpace", EventLogger.EventType.PointerEvent);
```

2022-10-06 19:56 UTC, bastianilso commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +    protected int controllerInsideBoundaries = 1;
These integers are only read and never set. I don't think we will need them, see my other comment.

2022-10-06 19:56 UTC, bastianilso commented on Assets/Scripts/Pointers/Pointer.cs
> +            {"ControllerHoverBoundaries", "NULL"},
Not neccessary, see other comment.

2022-10-10 05:23 UTC, bastianilso requested changes
Code changes look much better and simpler now,  only one part left.

2022-10-10 05:23 UTC, bastianilso commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +public class BubbleDisplay : Pointer
unless we have a good reason to change the class inheritance, this should remain `public class BubbleDisplay : MonoBehaviour`.

2022-10-10 09:07 UTC, Xav1204 commented on Assets/Scripts/Pointers/BubbleDisplay.cs
> +public class BubbleDisplay : Pointer
@bastianilso It's good, I changed the class inheritance. I tested to see the difference between the private LoggerNotifier class instance and the class inheritance Pointer. I forgot to change it after my test. Sorry.

2022-10-10 12:46 UTC, bastianilso approved these changes
I think this looks good now.

2022-10-10 12:46 UTC, merged