FadingHelpers.cs class and FadingUtils.cs static class added
med-material/Whack_A_Mole_VR pull request #219
Opened 2022-10-14 08:49 UTC by lucasmnt

Theses classes are used to handle different fading effects for different game objects.

Right now these scripts are not used by any game objects since they are subject to (a lot of?) change, but adding them won't do any harm to the existing project.

FadingHelper script can be attached to a game object and will look like this : 

![image](https://user-images.githubusercontent.com/94845309/195802602-dcb27d41-1ce0-4f0c-bcae-e46456117aa6.png)

Here is the purpose of the different parameters : 

- objToFade : drag and drop here the game object that you want to fade in or fade out
- Play Automatically : is still a work in progress, but will be used to fade in or fade out objects when they are enabled/disabled
- Fade in speed : ratio from 0 to 2 increasing/decreasing fading in effect speed
- Fade out speed : ratio from 0 to 2 increasing/decreasing fading out effect speed
- Fade delay : gives a delay between a fade in and a fade out
- Fade action : is used to setup which fade affect you are interrested in for the current gameobject the script is attached to

These scripts can be found in the project hierarchy here : **Assets>Scripts>Game**.

2022-10-14 12:02 UTC, bastianilso commented
Thanks for uploading this @lucasmnt . It's now more clear to me what you are trying to do. I think we are still talking past each other - and I think we may need to adjust your architecture to be a little simpler. Please take a look at my proposal and let me know what you think. 🙂

FadingUtil: a static class. It is technically designed to allow fading in and fading out for many different objects.
Public functions:

`FadingUtil.Fade(object Obj, float time, Fade fadeDirection, float fadeDelay=0f, bool setEnable = false)`

- FadingUtil.Fade() is a function which fades an object. Behind the scenes the Fade() function does the following: 1) Evaluates which type of object the passed object is and 2) starts an IEnumerator which fades the object over the course of X seconds (defined by the `time` variable). It either fades in or fades out, based on the specified `fadeDirection` (an enum which specify directions, e.g. `Fade.In` or `Fade.Out`).

Now, as for FadingHelper: This is a class in the "classical Unity component" sense. The class is technically designed to be added to game objects via the "Add Component" button, to make applying a fade easier. A convenient "Play Automatically" button makes it possible to fade object automatically, with no need for extra code. It provides following public functions:

`FadingHelper.Fade`

 - FadingHelper.Fade() takes no arguments. Instead it relies on the values of variables exposed by the component in Unity. Internally, FadingHelper actually utilize `FadingUtil` behind the scenes, to perform the fade. FadingHelper's purpose is merely to "make it easy" to fade objects, without need for code.


The point of this architecture is to 1) make it very clear what the purpose of the classes are and 2) simplify the code architecture and exposure points. And feel free to write up a counter proposal, if you have cases you feel are not currently covered or questions. 🙂

2022-10-20 07:31 UTC, lucasmnt commented
Hello @bastianilso, 

I'd like to ask you what is the purpose of "bool setEnable = false"  parameter for the Fade function :
> FadingUtil.Fade(object Obj, float time, Fade fadeDirection, float fadeDelay=0f, bool setEnable = false)

That being said, I've been working on FadingUtils/Helper classes and i've made good progress. Right now, here what the interface of FadingHelper looks like : 

![image](https://user-images.githubusercontent.com/94845309/196881676-11b79619-3840-441a-a46d-9165293277dd.png)

Purpose of the different parameters : 
- objToFade (gameObject) : drag and drop here the game object that you want to fade in or fade out ;
- Play Automatically (bool) : is still a work in progress, but will be used to fade in or fade out objects when they are enabled/disabled (maybe will be replaced by "setEnable" ?) ;
- Fade Time (float) : set up the duration of the fading effect ;
- Fade Delay (float) : gives a delay before a fade in and a fade out effect ;
- Fade Action (enum : In / Out) : is used to setup which fade effect you are interrested in for the current gameobject the script is attached to ;
 
Fade in speed and Fade out speed have been removed since we can now precisely ask for an exact duration for the fading effect.

In visual Studio here is the signature of the function in fadingHelper class : 

![image](https://user-images.githubusercontent.com/94845309/196883172-44c85037-1469-4e35-8d36-07f9dc961e74.png)


As you can see (and as you asked) I called directly the fade function from FadingUtils class, and it is working well. Here is the signature of the Fade( ) function from fadingUtils : 

![image](https://user-images.githubusercontent.com/94845309/196883730-7c3c3940-d869-4883-becb-3f7cc145118a.png)


The first parameter of this function is a reference of a MonoBehavior object, and is mandatory to have if we want to use Coroutines and IEnumerator in general inside a static class.

2022-10-24 11:21 UTC, bastianilso commented
Try to unify your individual functions by having a function which evaluates what 
https://github.com/med-material/Whack_A_Mole_VR/blob/master/Assets/LoggingManager/LogStore.cs#L321

![image](https://user-images.githubusercontent.com/3967945/197514682-5d9885a2-8c9f-4329-8088-a660aee68942.png)

2022-11-14 09:06 UTC, bastianilso commented
@lucasmnt is this ready for review? i still see a lot of code in FadingHelper.cs that I think we discussed moving to FadingUtils.cs

2022-11-21 11:57 UTC, bastianilso requested changes
Hi @lucasmnt, I had a brief look at your code in its current state.

For FadingHelper.cs, I agree that it looks mostly done, nice work. I have just a few comments about performing minor cleanups, which mostly touch upon how FadingHelper interacts with FadingUtils.

As for FadingUtils, I believe you still have some reduction you want to do (trying to create one single IEnumerator, rather than 10 different ones), but let me know you think its as reduced as you can make it, and I will give feedback on it.

2022-11-21 11:57 UTC, bastianilso commented on Assets/Scripts/Game/FadingHelper.cs
> +}
In the final version, please remove these outcommented code pieces.

2022-11-21 11:57 UTC, bastianilso commented on Assets/Scripts/Game/FadingHelper.cs
> +    private FadingUtils.FadingUtils.FadeAction fadeAction = FadingUtils.FadingUtils.FadeAction.In;
you could declare this enum prior to the `FadingUtils` class, instead of inside FadingUtils class, to make it less of a hassle to refer to it from `FadingHelper`.

2022-11-21 11:57 UTC, bastianilso commented on Assets/Scripts/Game/FadingHelper.cs
> +        FadingUtils.FadingUtils.FadeRoutine(this, objToFade, fadeTime, fadeAction, fadeDelay, setEnable, playAutomatically);
Why does all calls have to be `FadingUtils.FadingUtils.X()` ? is it not possible to just call `FadingUtils.X()` ?

2022-11-24 07:36 UTC, bastianilso requested changes
Check my comments. 🕶

2022-11-24 07:36 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +            case (ComponentToFade)0:
What would happen if we had this switch() statement inside `FadeInColor`?

2022-11-24 07:36 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +                    canvasGroup.alpha=SetAlphaToZero(); // alpha to zero
Why do we always `SetAlphaToZero()` ? Couldn't this be handled as a step within the call to `FadeInColor()` ?

2022-11-24 07:36 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +                    canvasGroup.alpha=SetAlphaToNormal(baseAlpha);
`SetAlphaToNormal(baseAlpha)` doesnt seem to do something, but correct me if I'm wrong.  It seems to just return the value it receives.

2022-11-24 07:36 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +            case (ComponentToFade)1:
When you evaluate the cases, it is just as fast to just call `ComponentToFade.Image`. C# converts this automatically to its underlying numerical value.

2022-11-24 10:34 UTC, bastianilso commented
summary: think about how to abstract away "how to fade" from "reading alpha value" and "setting alpha value". Think of "reading/setting" as two functions. 

- FadeRoutine(): Starts a Fade routine
- IEnumerator FadeGameObject: Does the actual fading over a given time, with a given delay, from starting point X to ending point Y..
- SetAlpha(object gameObject, float alphaVal): Function which takes an object, identifies what it is (fx by reading the enum var), and changes its alpha value to X.
- ReadAlpha(object gameObject): Function which takes an object, identifies what it is (fx by reading the enum var) and returns its alpha value.

then collapse FadeGameObject into just one code for Fade in and one code for Fade out.

2022-12-01 09:04 UTC, lucasmnt commented
All the details here are from the FadingUtils.cs class, and are mainly a direct anwser to your last comment.

**FadeRoutine(): Starts a Fade routine**

For this part, not much has changed, from **FadeRoutine()** we fire a coroutine with the **FadeGameObject()** IEnumerator and all the necessary parameters. Inside the used parameters of the coroutine you can see a call to the function **FadeIdentification(Obj)** which will return a ComponentToFade enum value that identifies what object are we working with (and that would be a CanvasGroup/Image/SpriteRenderer/MeshRenderer/Text).

![image](https://user-images.githubusercontent.com/94845309/205000223-091d413d-023a-44e7-b73d-0662e1744527.png)


**IEnumerator FadeGameObject: Does the actual fading over a given time, with a given delay, from starting point X to ending point Y..**

In this function, I use a switch case depending on the fadeAction parameter that determines if we are working on a fade in effect or a fade out effect, and that will then call the correct function accordingly. 

![image](https://user-images.githubusercontent.com/94845309/205007458-de06a741-0242-434c-bc22-768f762348dd.png)


The functions that are called are **FadeInColor3()** and (or) **FadeOutColor3()** and basically what is happening in these functions is the generalisation of the 5 fade in functions and 5 fade out functions that I had in previous version of my work. These functions use both the new **SetAlpha** and **GetAlpha** functions that I will be detailing more below. There is also a last new function called **FadeInAlpha** (or **FadeOutAlpha**) that will be acutally used to shift the alpha towards 0 or 1 depending on the need. Here what the functions look like :

![image](https://user-images.githubusercontent.com/94845309/205009090-dea57c9c-3d6f-4061-84e1-b381c7c18a91.png)

![image](https://user-images.githubusercontent.com/94845309/205009211-2cdefabe-6711-4529-a995-8802c9d9e03f.png)

![image](https://user-images.githubusercontent.com/94845309/205010341-64a2c3c2-a814-408d-be24-0f6e448be8f5.png)


**SetAlpha(object gameObject, float alphaVal): Function which takes an object, identifies what it is (fx by reading the enum var), and changes its alpha value to X.**

For the function SetAlpha(), I use three parameters : the object we are working with, the type of object it is from the enum ComponentToFade, and also the target alpha, which is the value we want the object's alpha changing to. With this I create a switch case that will make it possible to access and change the alpha value of any registered object.

![image](https://user-images.githubusercontent.com/94845309/205004243-6edf1241-0461-44b7-a54d-993cafd513e7.png)


**ReadAlpha(object gameObject): Function which takes an object, identifies what it is (fx by reading the enum var) and returns its alpha value.**

This is basically the same principle as SetAlpha() function, but I use here only two parameters, ComponentToFade enum and the object we are working with, so the function returns the object's aloha value.

![image](https://user-images.githubusercontent.com/94845309/205005755-a1f7c565-d7f6-4d91-9480-9fcd384005b3.png)

2022-12-02 09:06 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
`FadeGameObject3` is already a coroutine. Think of it as a separate process you created that runs in parallel to Unity. Right now you make another call within that separate process, which starts another separate process called `FadeOutColor3`. That means two separate processes for every fading object.

I think it's cleaner to structure the code so you only need to start one `IEnumerator` per fade - this way there is a clear mapping between number of fades and number of IEnumerator coroutines you start. So I would call `FadeInColor3` as a regular function. Or even better: merge `FadeInColor` with `FadeInObject` since FadeInObject currently doesnt do much on its own (in your switch statement, both cases lead to the same call to FadeOutColor3, with exact same parameters).

2022-12-02 11:15 UTC, lucasmnt commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
That is true what you say about FadeGameObject coroutine, and since it's just doing a switch case, I can make it a simple function that will fire the coroutine FadeInColor or FadeOutColor.

2022-12-05 07:35 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
@lucasmnt that's fine for me too. 👍

2022-12-05 09:27 UTC, bastianilso requested changes
ok @lucasmnt I think by now, what should be done here is to do a general cleanup - removing old commented out code, any Debug.Log() calls, removing assets for internal testing use and squashing your commits together into a single commit with an appropriate title and message.

2022-12-05 09:27 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    }  // sets alpha value of an object
Consider assigning Obj.GetComponent<> to a variable with a short name like "comp" and use `comp.r, comp.g, comp.b` . This will make each line less dense improving readability, which I think in this case is a fair tradeoff.

2022-12-06 07:49 UTC, bastianilso requested changes
Hi @lucasmnt some additional comments. 🌴🌴🕶🍹

2022-12-06 07:49 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to fade out then disable an object
The public function `DisableAutomatically` just makes a call to `FadeRoutine` which is already a public function. We could just as well call FadeRoutine() from FadingHelper instead and pass the proper parameters.

2022-12-06 07:49 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to transform numbers from a range to numbers from another range
I think we can simplify this if we rely on Unity's existing mathemathics package and use the `remap` function from there, can you check?

https://docs.unity3d.com/Packages/com.unity.mathematics@1.2/api/Unity.Mathematics.math.remap.html

2022-12-06 07:49 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
Could we merge FadeRoutine and FadeGameObject? Just asking since all FadeRoutine does is basically to call FadeGameObject. We could then make the FadeIdentification() call a step within that function.

2022-12-06 08:25 UTC, lucasmnt commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to fade out then disable an object
I do agree with that, I made this function so it is very simple to do the fading then disabling process. To me it was more clear what to do without having to play with the parameters.

2022-12-06 08:25 UTC, lucasmnt commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
Yes, it can be done, here what it looks like now : 

![image](https://user-images.githubusercontent.com/94845309/205858181-438e5114-24e9-4dd0-b0eb-0f6be1d9e56b.png)

I'm basically using the FadeGameObject function, and calling the FadeIn/FadeOutColor function with the FadeIdentification() call within it.

2022-12-06 08:30 UTC, lucasmnt commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to transform numbers from a range to numbers from another range
It seems that the package Unity.mathematics exists, but it has to be manually added to the project using "Add package from git URL..." option. Should I try it or should I let it be ?

2022-12-06 10:19 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    }
fine with me

2022-12-06 10:22 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to transform numbers from a range to numbers from another range
try it, let's see how it works out. 🙂

2022-12-06 10:24 UTC, bastianilso commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to fade out then disable an object
@lucasmnt if you want to make it more clear for others you can change the variables "setEnable" and "playAutomatically" from being booleans, to being enums with two states. "AutoPlay.Off", "AutoPlay.On", "SetEnable.Off", "SetEnable.On".  This is much clearer and reads a lot better in function calls than "true, true".

2022-12-07 09:33 UTC, lucasmnt commented on Assets/Scripts/Game/FadingUtils.cs
> +    } // function used to transform numbers from a range to numbers from another range
I've been testing it, first I installed it, no problems, then I tried to use the the Remap function of the Unity.Mathematics instead of my MapRange() function, and it seems to work as intended. 
I mean, I have the same result than if I was using the MapRange() function, the only difference is the calling of the function : 

![image](https://user-images.githubusercontent.com/94845309/206140204-df1c4417-42d9-4fb4-9395-64a00a42b7de.png)


I also tried to see if one of the functions ran better than the other by looking at the fps when fading a lot of objects at the same time, but it seems that it doesn't to have a significant impact either.

2022-12-09 10:22 UTC, lucasmnt commented
I made some modifications to the parameters of some functions of the fadingUtils class, and parameters to the fadingHelper class :
 
![image](https://user-images.githubusercontent.com/94845309/206670425-e94cb81a-7fca-423e-8cd6-e08432c5da99.png)

![image](https://user-images.githubusercontent.com/94845309/206670643-4d3afa57-bc22-4686-bf8a-9a3fe4d19af9.png)


Now, we can pass "On" or "Off" for the setEnable and playAuto parameters, which is more readable than a "true" or "false".

However, I still have a problem with the playAuto parameter and disabling the object, let me explain : we want an object to automatically play its fade effect when it is enabled/disabled. In the use cases what makes sense is **fading in** an object when it's **enabled** and **fading out** an object when it's **disabled**.

For the enabling part, there is no problem : 

![image](https://user-images.githubusercontent.com/94845309/206675198-c79256fe-0819-43ee-a90c-45da1715c586.png)


Using the built-in OnEnable() function from Unity works perfectly fine, allowing us to fade-in an object when we are enabling it, and not necessarily having to call the Fade() function directly. Plus this only happens when autoPlay is set to "On".

The problem comes with disabling the object : 

![image](https://user-images.githubusercontent.com/94845309/206675857-93251685-a7fe-4af2-b934-7870f06caa60.png)


Indeed, following the same principle, I wanted to be able to fade out the object without having to actually call for Fade(). The thing is that OnDisable() function plays **after** the object gets disabled, so how can one fade the object first then disable the object automatically, in the same manner as the fading in case ?

My take on this problem was to make a specific function to call that would do the fading out then disabling, but can we really call it an autoPlay feature since we'll have to call this somewhere in the code ? 
I mean, we can argue that it is / it is not an autoPlay feature when calling the fading in effect inside OnEnable() but will it make sense ?
The thing that I don't like is that the methods and process will not be the same for the two different use cases and i'm afraid that could be confusing : 
Like why can I just use gameObject.setEnable(true) and have an "auto" fade in effect, but to have my fading out effect + object disabling, why do I have to call explicitly FadingUtils.FadeRoutine() with the correct parameters ?

I hope what i just wrote makes sense to you, because i'm not sure on how to handle this problem (if it is even a problem).

2022-12-09 11:35 UTC, bastianilso requested changes
Hi @lucasmnt, 99% done, have a look.

2022-12-09 11:35 UTC, bastianilso commented on .gitignore
> +/Assets/Scripts/Game/TestScript.cs.meta
are you adding the files to gitignore because you want to keep them on locally on your disk? you can also just not commit them in the first place (git doesnt force you to commit every file). But if this is easier for you to manage, I'm fine with it (it means gitignore will specify some files that will never be present on others system, thats all).

2022-12-09 12:15 UTC, lucasmnt commented on Assets/Scripts/Game/FadingHelper.cs
>          }
Yeah I think so too, I backed down my work that used only a if statement and it looks cleaner/simpler : 

![image](https://user-images.githubusercontent.com/94845309/206699486-b5d57638-2a3e-41de-9ad5-0c4c652f7fdf.png)


I'll keep this for the next commit.

2022-12-09 12:16 UTC, lucasmnt commented on .gitignore
> +/Assets/Scripts/Game/TestScript.cs.meta
Yes, I did this simply so I don't have to care anymore about these files being commited everytime I'm actually committing some new work into the project.

2022-12-12 08:33 UTC, bastianilso approved these changes

2022-12-12 08:33 UTC, merged