Randomly Mole Spawner System
med-material/Whack_A_Mole_VR pull request #223
Opened 2022-10-26 09:50 UTC by Xav1204

We needed to add a small animation on the wall to make the experience more immersive. Now, the mole spawn randomly on the wall surface.

The duration of the full wall filling is between 400 and 500 ms.

Updating of the functions name and incoherence in the code.

2022-10-26 10:00 UTC, Xav1204 commented
@bastianilso as the previous pull request had a lot of conflicts and unwanted files in the commit, I closed it and I created a new branch because we didn't have a lot of files to change. I added a little change. Indeed, in the previous pull request, I directly disabled diskmole Prefab and it's maybe a problem in the future because if we need to change something on diskmole prefab by enabling it and that we forget to disabled again the prefab, the animation won't work. This is why I added an instance of the diskmole and that I disabled it in the awake function like that, we can leave the diskmole prefab enable. I tried to do this in the start function but it didn't work, between 2 and 5 moles didn't appear. This is why I used the awake function.

Let me know if it looks good for you now.

2022-10-26 20:13 UTC, bastianilso commented
@Xav1204 another approach is to not disable/enable the objects with  "SetActive()" directly, but instead set the visibility of the mole by enabling/disabling its Renderer component. This way you are not interfering with any possible scripts, but merely just toggling its visibility. Or even better, we should keep the Renderer enabled but just manipulate the material so the diffuse opacity of the moles is 0 in the beginning. Then in the IEnumerator you can change the opacity to 1.

2022-10-27 11:51 UTC, Xav1204 commented
@bastianilso  I've tested your two approaches and by enabling/disabling the renderer component is like enabling/disabling the object. So, we can make one of them, there are no problem with these solutions.
However, change the a is more complex because we have two elements that compose the diskmole and one of them has an default material of which I didn't succeed to change is visibility. 
Moreover, by changing the material made the mole aspect strange so I think that is not a good for us.

Finally, for me, the best solution is to enabling/disabling the object or the renderer of the children.

Please, let me know what you want to do.

2022-11-02 07:48 UTC, bastianilso commented
@Xav1204 let's enable/disable the renderer then, I think that's cleanest and will not mess with any logic in the moles themselves.

2022-11-07 07:36 UTC, Xav1204 commented
![MoleAnimation](https://user-images.githubusercontent.com/73820233/200252033-56aa8541-229d-49fd-bde4-5cdf382ceeec.gif)
@bastianilso it's also good for this pull request.

2022-11-07 11:49 UTC, bastianilso requested changes
OK, almost there @Xav1204 . One more thing, I dont think this renderer solution is pretty in its current state. If it had been just a single function call to disable the mole's renderer, things would have been different, but I see that the complexity is higher than that and it might as well be worthwhile to implement this across all mole types, not just DiskMole, hence the logic should be placed in Mole.cs and not DiskMole.cs.

2022-11-07 11:49 UTC, bastianilso commented on Assets/Scripts/Game/WallManager.cs
> +                }
Rather than using for loops directly from WallManager to enable the renderer, I would rather have you define public functions in Mole.cs called something like `SetVisibility(true/false)`, so we hide away the details of how its done.

2022-11-07 11:49 UTC, bastianilso commented on Assets/Scripts/Moles/DiskMole.cs
> +        }
Let's define a function called `SetVisibility(true/false)` from Mole.cs instead and call that from Mole.cs' Awake(), so that all moles can use this feature in the future. We should also want a public bool called defaultVisibility which is set to false by default and which is checked in Awake, before manipulating the visibility itself.

2022-11-07 12:49 UTC, Xav1204 commented
@bastianilso I've made the changes that you asked me. Please, tell me if it's that you really expected.

2022-11-08 08:31 UTC, bastianilso approved these changes

2022-11-08 08:31 UTC, merged