Fix CurrentMoleToHitID mismatch
med-material/Whack_A_Mole_VR pull request #225
Opened 2022-11-01 13:57 UTC by Xav1204

The problem was that we saved the currentMoleID before to update its value. Therefore, for the first mole that spawned, we had a null value. Moreover, I've also modified the fake mole case because now we use distractor left or right instead of fake mole in the event type.

New Result :  
![image](https://user-images.githubusercontent.com/73820233/199250291-b0c500d5-8625-4ea1-9221-9c66ec8b796a.png)

2022-11-02 07:44 UTC, bastianilso requested changes
@Xav1204 CurrentMoleToHit encodes which mole the player is supposed to hit. The player is not supposed to hit Distractor moles, so therefore you should not call `UpdateCurrentMoleLog` when distractor moles spawn.

2022-11-07 07:27 UTC, Xav1204 commented
@bastianilso it's good for this pull request, you can merge it.

2022-11-07 10:58 UTC, bastianilso requested changes
@Xav1204 OK. I just have one additional comment.

2022-11-07 10:58 UTC, bastianilso commented on Assets/Scripts/Logging/EventLogger.cs
> -                SaveEventDatas(datas, true, true);
Why is SaveEventDatas removed from Mole Spawned? (I'm asking whether this has to do with fixing this issue or not, and why it was necessary, what role does it play).

2022-11-07 11:44 UTC, Xav1204 commented on Assets/Scripts/Logging/EventLogger.cs
> -                SaveEventDatas(datas, true, true);
![image](https://user-images.githubusercontent.com/73820233/200301570-431a3a93-f090-4cda-87e1-4c4cf5c2acd6.png)

@bastianilso, I don't know what happened but the SaveEventDatas function is still called. It's a necessary function that write the values in the Event csv file. Without it, we will have null values in this file.

2022-11-08 08:10 UTC, merged