New Data Saving System
med-material/Whack_A_Mole_VR pull request #232
Opened 2022-11-21 09:07 UTC by Xav1204

In the new saving system, we've deleted useless functions in the process and also reorganized it to work with the logstore and not with the loglist to save the datas in the different csv files.

2022-11-21 09:10 UTC, Xav1204 commented
@bastianilso I've created this pull request for the new saving system. 
Please tell me if it looks right for you.

2022-11-21 11:50 UTC, bastianilso requested changes
@Xav1204 removing `SaveLog()` removes public API from loggingManager. It should be possible to keep `SaveLog()` and still make the new data saving system work. If not, you will need to explain why in the pull request.

2022-11-22 08:41 UTC, Xav1204 commented
@bastianilso I have one question about the API. How does the API save files? Do we need to specify the file's label to save or the API recuperate itself all the logslist's label for creating a "for" loop to save all the logslist's datas?

2022-11-22 09:52 UTC, bastianilso commented
@Xav1204 `SaveLog` takes a specific `collectionLabel` as input and saves the specified collection. LoggingManager always saves one collection as one file. SaveLog Accesses the` logStore` by performing a lookup on `logsList` using `collectionLabel`. After saving the logStore, if `clear` is `true`, then the entry is removed from `logsList`. If the entry was `Meta`, we can call the CreateMetaCollection function again within LoggingManager.

Is this what you asked for?

2022-11-22 09:56 UTC, Xav1204 commented
@bastianilso thanks for your answer. I will see what I can do with this function for the multi saving system.

2022-11-23 13:11 UTC, Xav1204 commented
@bastianilso I've made changes. So, as we delete the different logsList's element in the SaveLog function. If we use a foreach loop in SaveAllLogs function, we have a problem because the number of elements has changed duriing the save and a compilator error appeared. Therefore, I now store the differents logsList's labels in a list and when the label to save = the last label in the list, I clear the list for the next save. Moreover, as the sql saving system isn't operational, I didn't make the changes for this kind of save. Do I need to make changes for the sql save?

2022-11-23 13:25 UTC, bastianilso requested changes
Nice progress @Xav1204 🍹 I have some comments for you, see below.

2022-11-23 13:25 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +    }
`labelList` is introduced to solve the problem that `SaveAllLogs()` cannot make a foreach loop across `logsList` anymore. So why is `labelList` a global variable? Couldn't it be a local variable defined within `SaveAllLogs()` ?

2022-11-23 13:25 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +            }
I don't see why `SaveLog()` need to make changes to labelList, when labelList is only used by `SaveAllLogs()`. See my other comment.

2022-11-23 13:25 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +            logsList.Remove(collectionLabel);
Right now you first call `Save()` and then remove the collection.
This means that `Save()` has to finish executing before we remove the collection.
Even if saving itself is asynchronous, I think it's cleaner to:

1. store the LogStore object you get from `logsList[collectionLabel]` in a local variable.
2. call `logsList.Remove(collectionLabel)`
3. then call `Save()` 

This way, you make it clear from the flow of the code that the logslist entry was already removed before any operations related to saving continues.

2022-11-24 08:14 UTC, Xav1204 commented
@bastianilso I've made changes. I think it's right now.

2022-11-24 08:51 UTC, bastianilso requested changes
looks much better @Xav1204, few more observations, please take a look. 🏖

2022-11-24 08:51 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +        onSaveInfoChanged.Invoke(saveStateInfo);
Since the entry removal of `logsList` and the passing of the logStore now happens in `SaveLog()`, it would make a lot of sense, if it was also `SaveLog()` which trigger a SaveInfoChanged announcement. And it would solve the situation that if users call `SaveLog()` directly, there is no SaveInfoChanged announcement currently.

2022-11-24 08:51 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +            }
Please add a code comment here, explaining that we create the Meta collection immediately again, because the Meta collection is a special log collection which LoggingManager always create, containing meta information about the logging process.

2022-11-24 08:51 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
>              SaveCallback(logsList[label], clear);
Why does `SaveCallback()` still use `logsList[label]` ? shouldnt it use the `logStore`?

2022-11-24 08:51 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +        logStore.Clear();
Why do we call `logStore.Clear()` in `SaveCallback()`? We don't need to clear it anymore do we?

2022-11-24 09:20 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
>              SaveCallback(logsList[label], clear);
It's the SaveCallBack function called in the SaveToSQL function. I didn't change this function because I didn't have the way to test changes. So I don't know if I need to change this one? I can do it but I won't be sure about the result.

2022-11-24 09:23 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +        onSaveInfoChanged.Invoke(saveStateInfo);
As I said, I've created a issue to improve the system when we try to quit the app before that the save is done because it's now obsolete with the new multi saving system and I wanted to do this change in this issue. Please, tell me what do you think about that?

2022-11-24 10:55 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
>              SaveCallback(logsList[label], clear);
thanks @Xav1204, I think it's safe to make the changes, as long as the API of `SaveCallback()` and API of the `ConnectToMySQL` doesnt change.
I am currently trying to find my notes for connecting to the server and will attempt to update the database, so that we can test the code.

2022-11-24 11:54 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
>              SaveCallback(logsList[label], clear);
@bastianilso If I remove logStore.Clear() in the SaveCallBack function as you asked to the next comment, the API of this one will change because we won't need parameters clear and logstore in the function. Moreover, in the old version, this function was used to clear the logStore but now, I clear the key and values in logsList directly and if I remove logStore.Clear() we can just rename this function in UpdateSaveInfos() because without this element, the function just update the save's informations. So, please tell me what do you think about this issue.

2022-11-28 15:21 UTC, bastianilso requested changes
looking really good @Xav1204, one small change and it's ready to go.

2022-11-28 15:21 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +            Debug.Log(collectionLabel + " length : " + logsList[collectionLabel].RowCount);
please remove this debug log. 🌴

2022-11-29 07:51 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +            Debug.Log(collectionLabel + " length : " + logsList[collectionLabel].RowCount);
@bastianilso it's good, I've removed the debug.log. Do you need that I write a little feedback in this discussion to explain the point of calling EndRow function if logType = OneWriteRow ?

2022-11-29 08:00 UTC, bastianilso commented on Assets/LoggingManager/LoggingManager.cs
> +            Debug.Log(collectionLabel + " length : " + logsList[collectionLabel].RowCount);
@Xav1204 i think if you add a small code comment about it next to the if statement, then it will be clear for future developers who might need to read the code.👍

2022-11-29 08:29 UTC, Xav1204 commented on Assets/LoggingManager/LoggingManager.cs
> +            Debug.Log(collectionLabel + " length : " + logsList[collectionLabel].RowCount);
@bastianilso I've put some comments about this part in the code.

2022-11-30 08:01 UTC, bastianilso approved these changes

2022-11-30 08:01 UTC, merged