Fix Bug and add one event in Event.csv
med-material/Whack_A_Mole_VR pull request #247
Opened 2023-02-03 10:35 UTC by Xav1204

@bastianilso For this pull request.
The first thing that I've made is to add the event " Controller Main Set + controllerName" in Event.csv. To do this, I've created a function in modifiersManager to log the event in event.csv and I call it in gameDirector after having log "Game Started" because it made sense to log what controller we use after having log "Game started".
![image](https://user-images.githubusercontent.com/73820233/216576572-6126e90d-0247-4ef0-b964-ce3bff1fa9a6.png)

The second thing that I've made is to add in Event.csv and Sample.csv the columns ControllerLeftLaser.
So I've changed the code because to store the logTracker component in the list, we used a specific function that search the component on the scene but the problem was that if the parent object is disabled, the function won't find the component.
I've changed the inheritance of TrackerHub on Monobehaviour to add it on EventLogger Object : 
![image](https://user-images.githubusercontent.com/73820233/216577251-6c2bd1e2-475d-44d2-8fe6-8447666cfc95.png)
In this script, we now add the object directly in the list for not having problem. As the two others scripts are a component of EventLogger, we just get the component directly on the parent.

Let me know if something can be improved.

2023-02-03 11:10 UTC, bastianilso requested changes
Hi @Xav1204 nice work, have a look at my comments.

2023-02-03 11:10 UTC, bastianilso commented on Assets/Scripts/Game/ModifiersManager.cs
> +
Rather than calling a custom function from gameDirector, I think it might be better to change the default value of `controllerSetup` to be `  private ControllerSetup controllerSetup = ControllerSetup.Off;`. Then Awake will call the function `SetControllerEnabled(ControllerSetup.Right);` (it looks like it already does this). Could you check if that solution is feasible?

2023-02-03 11:10 UTC, bastianilso commented on Assets/Scripts/Logging/TrackerHub.cs
> +    [SerializeField]
Does changing the inheritance affect the logging itself? Or does it make no difference?

2023-02-03 11:11 UTC, Xav1204 commented on Assets/Scripts/Logging/TrackerHub.cs
> +    [SerializeField]
@bastianilso we have no difference in the logging.

2023-02-03 11:23 UTC, Xav1204 commented on Assets/Scripts/Game/ModifiersManager.cs
> +
@bastianilso the problem by doing this is that it will work only for the first game. If the therapist run another game, the log won't appear. This is why I've created a function, like that, we have the log for every games that the therapist run.
I will try to find something different.

2023-02-03 11:58 UTC, bastianilso commented on Assets/Scripts/Game/ModifiersManager.cs
> +
@Xav1204 ah, thanks for the explanation, I did not think about this scenario.
Another simpler option is to simply let  `SetControllerEnabled` log every time it is called, regardless of whether state changed. We can then  infer in the analysis whether that actually changed.

2023-02-03 11:58 UTC, bastianilso commented on Assets/Scripts/Logging/TrackerHub.cs
> +    [SerializeField]
@bastianilso OK. 👍

2023-02-03 12:05 UTC, Xav1204 commented on Assets/Scripts/Game/ModifiersManager.cs
> +
@bastianilso Another problem that we have is that the loggerNotifier is in the function SetMainController and not SetControllerEnabled and I tried to change the loggerNotifier in SetControllerEnabled but it doesn't work.

2023-02-03 12:43 UTC, bastianilso commented on Assets/Scripts/Game/ModifiersManager.cs
> +
@Xav1204 aaah, I see what is happening here.Actually whether a controller is enabled and whether it is main is two different concepts. It's legacy and a bit ugly..
Maybe we can log every time SetControllerMain is called instead?

2023-03-29 11:49 UTC, bastianilso commented
A modified version of this branch was rebased to master via commit 11924a120d637124de46354dba577c29faaa0638

2023-03-29 11:49 UTC, closed without merging